import './globals.css';

import { Analytics } from '@vercel/analytics/next';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { I18nProvider } from 'next-i18next/client';
import { generateI18nStaticParams, getResources, getT, initServerI18next } from 'next-i18next/server';

import i18nConfig from '@/next-i18next.config';

initServerI18next(i18nConfig);

export async function generateStaticParams() {
    return generateI18nStaticParams();
}

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}>) {
    const { locale } = await params;

    const { i18n } = await getT();
    const resources = getResources(i18n);

    return (
        <html lang={locale}>
            <body>
                <I18nProvider language={locale} resources={resources}>
                    {children}
                </I18nProvider>

                <Analytics />
            </body>
        </html>
    );
}
